### ISSUE TITLE
zxcvbn via headless norns(64bit)

### ISSUE THREAD

**Issue by LarryBoy1975** [schollz/zxcvbn#24]
I'd love to try zxcvbn but in order to do so i have to go through norns:)  i've got a RPi4 and your headless-hack(https://schollz.com/blog/norns/) installed but have encountered a few speed bumps.  Do you have any advice to get around.... "/home/we/dust/code/zxcvbn/lib/cjson.so: wrong ELF class: ELFCLASS32"? 

   error loading module 'cjson' from file '/home/we/dust/code/zxcvbn/lib/cjson.so':
	/home/we/dust/code/zxcvbn/lib/cjson.so: wrong ELF class: ELFCLASS32
stack traceback:
	/home/we/norns/lua/core/norns.lua:146: in function </home/we/norns/lua/core/norns.lua:146>
	[C]: in ?
	[C]: in function 'require'
	/home/we/dust/code/zxcvbn/zxcvbn.lua:28: in main chunk
	[C]: in function 'dofile'
	/home/we/norns/lua/core/script.lua:198: in function </home/we/norns/lua/core/script.lua:198>
	[C]: in function 'xpcall'
	/home/we/norns/lua/core/norns.lua:147: in field 'try'
	/home/we/norns/lua/core/script.lua:198: in function 'core/script.load'
	/home/we/norns/lua/core/menu/preview.lua:23: in function 'core/menu/preview.key'
	/home/we/norns/lua/core/menu.lua:144: in field 'key'
	/home/we/norns/lua/core/osc.lua:92: in upvalue 'remote_handler'
	/home/we/norns/lua/core/osc.lua:107: in function </home/we/norns/lua/core/osc.lua:100>
# script clear
lua: /home/we/norns/lua/core/clock.lua:58: bad argument #1 to 'resume' (thread expected)
stack traceback:
	[C]: in function 'coroutine.resume'
	/home/we/norns/lua/core/clock.lua:58: in function 'core/clock.resume'

**Comment by schollz** [comment]
yeah its bundled with a cjson that is not compatible with your arch.

I just pushed a change to fix

```
cd zxcvbn/lib
make all
```

you might need to install liblua5.3dev first 

```
sudo apt install liblua5.3-dev
```

**Comment by LarryBoy1975** [comment]
That worked immediately!

**Comment by LarryBoy1975** [comment]
I'm already floored by your gifts and hate to impose, but you are obviously the best person to ask... i'd like to see a gamepi-type hats can run norns on a Rpi4 (eventually CM4 w/cm4-nano-b). I guess id need to learn how to reasign the GPIO assignments and from what I can tell these may be handled by an overlay. Do you have any suggestions that may help me?  The norns shield looks neat and I probably will try to get one but those GamePi options are plentiful and I can see that being a fun alternative for someone like me, interested in a pocket-DAW-tracker.  

P.S. I haven't had a chance to play with zxcvbn yet, but it looks amazing! Thank you!

**Comment by schollz** [comment]
here's the original shield instructions: https://github.com/monome/norns-shield

making your own is possible. its been done (e.g. see this project: https://github.com/okyeron/fates or this project: https://llllllll.co/t/my-custom-battery-powered-norns-shield-the-omnibus/55736). its also not easy. the audio codec stuff is baked into the norns image so not only do you have to reroute GPIOs you'll also need to rewrite the norns image (probably fork this: https://github.com/monome/norns-image). that's all I can really say about it except that its potentially a big project, compared to sourcing the parts to build the original shield.

**Comment by LarryBoy1975** [comment]
Looks like I need to buy the shield.   zxcvbn loads up but it doesn't respond to the keyboard.

**Comment by schollz** [comment]
Do you use docker? It's pretty easy to get it working in the browser form docker

**Comment by LarryBoy1975** [comment]
Thanks for helping me realize that norns is locked up:(  Your tracker looks really neat, it's what made me take a stab at norns. You should find a different platform and make zxcvbn your own.

**Comment by schollz** [comment]
don't agree its locked up at all- I mean zxcvbn can run through a browser and works perfectly fine https://play.norns.online/ (there is audio latency through the public internet, but no latency if run locally)

**Comment by LarryBoy1975** [comment]
"locked up" refers to: "baked into the norns image". Not saying you can't have fun, there is just a limit. anyway, i found some easier options for me, Sound Pi and most amazingly, Renoise on RPi.  Renoise was exactly what i've been looking for. Good luck sharing your coded love with the masses.  Thanks for helping resolve my issues.
