### ISSUE TITLE
Function key does not open menu

### ISSUE THREAD

**Issue by niksilver** [schollz/zxcvbn#25]
zxcvbn is an incredible piece of work. Congratulations and thank you. Unfortunately, here is a bug.

**Describe the bug**
1. I am in zxcvbn and am editing a script
2. I read that [I can hit a function key](https://zxcvbn.norns.online/#menu-invocation) to open a menu.
3. I hit 'Fn' + 'F4' on my keyboard.
4. No menu appears. Also...
5. ...In maiden on my laptop (which is connected to norns.local) I see an error message (below).

```
lua: 
/home/we/dust/code/zxcvbn/zxcvbn.lua:470: bad argument #1 to 'find' (string expected, got nil)
stack traceback:
	[C]: in function 'string.find'
	/home/we/dust/code/zxcvbn/zxcvbn.lua:470: in function 'core/keyboard.code'
	/home/we/norns/lua/core/keyboard.lua:130: in function 'core/keyboard.process'
	/home/we/norns/lua/core/hid.lua:177: in function </home/we/norns/lua/core/hid.lua:162>
```

**System log**
Attached.

[system.log](https://github.com/schollz/zxcvbn/files/10735659/system.log)

Thanks for your amazing work.

**Comment by schollz** [comment]
Seems like your keyboard doesn't have full support? What kind of keyboard is it?

**Comment by niksilver** [comment]
Thanks for the quick reply. My keyboard is a [Keychron K8 UK ISO layout](https://www.keychron.uk/products/keychron-k8-wireless-mechanical-keyboard-uk-iso-layout). It is new, which means I may be misunderstanding its intricacies somewhat. (However, I can confirm it works fine with my Windows laptop.)

Some further details:
1. The K8 has an option to swap the way the function keys work. In "function key mode" hitting `F1` etc without a modifier will produce the function key, and hitting `Fn`+`F1` etc will produce the corresponding mulitmedia operation. In "multimedia mode" the `Fn` modifier has the opposite effect with each function key. However, the above error occurs in either mode, and only when hitting the key combination to get `F4`. When hitting the key combination to get the multimedia operation maiden remains silent.
2. I have submitted [a pull request](https://github.com/monome/norns/pull/1651) to the norns core to add a UK keyboard layout. The above error occurs whether I use my new UK keyboard layout or the original norns US keyboard layout. The pull request doesn't change anything about the function keys, by the way.
3. The above error also happens for function keys `F1` to `F9`.
4. When the keyboard is in "function key mode" then when I hit `F10`, `F11` and `F12` maiden reports mute, volume down and volume up respectively, which are their multimedia operations - even though the function keys should be produced. And the opposite occurs when the mode is switched...
5. When the keyboard is in "multimedia mode" then when I hit `Fn'+`F10`, `Fn`+`F11` and `Fn`+`F12` maiden reports mute, volume down and volume up respectively, which are their multimedia operations - even though the function keys should be produced.

I hope that makes sense.

**Comment by niksilver** [comment]
Ah, further experimentation reveals this does not happen when the keyboard is switched to MacOS mode (a physical switch on the side - the other option is Windows/Android). In MacOS mode `F4` etc does send an F4, although it switches out to a top level norns menu - it isn't picked up by zxcvbn. In Windows/Android mode the function `keyboard.code(k, v)` can be called with a value of `nil` for `k` - and that's what produces the error [at this line](https://github.com/schollz/zxcvbn/blob/main/zxcvbn.lua#L470).

So this is obviously something to do with the way the norns handles this particular keyboard. As a workaround it would be nice if `keyboard.code()` would handle `k` being `nil` (and produce an error in maiden), but clearly the main issue is not with zxcvbn.

Apologies for the somewhat wild goose chase.
