### ISSUE TITLE
PSET function locked and scanning

### ISSUE THREAD

**Issue by hvij1228** [schollz/zxcvbn#30]
**Describe the bug**
PSETs get limited to the  number of existing saved PSETs and no more can be saved. All other functionality remains the same. However, the delete function only takes effect after reseting the norns shield. No new saves can be made.

Additionally, attempting to load a different script generates a screen that reads "scanning...." and never loads the script menu. The screen times out and goes back to the "SELECT/SYSTEM/SLEEP" screen.

Only restarting allows the norns to return to the full script menu.

**System log**
Follow [these instructions](https://monome.org/docs/norns/help/#logs) to capture your system log and attach it here.
//////// current boot

[system.log](https://github.com/schollz/zxcvbn/files/13780330/system.log)

**Comment by hvij1228** [comment]
Issue appears to have resolved with a deletion of some PSETs via Samba. There may have been corrupted PSETs that were preventing normal operation of the norns.

**Comment by schollz** [comment]
thanks!! that's great to hear, not sure how they got corrupted though :(
