### ISSUE TITLE
archive not working 

### ISSUE THREAD

**Issue by rbrt-fm** [schollz/zxcvbn#7]
been having a blast learning zxcvbn, thank you for the amazing tool.

i tried saving something as an archive last night, but it didn't seem to work correctly. when i go to load the archive, it creates another archive and wont load in any of the text or the clade selections to the tracks. it does however load the text to the `data/zxcvbn/pages` files, so at least i know its saving something. this is a factory norns fwiw. i attached the system log and the archive. thanks zach!

[system.log](https://github.com/schollz/zxcvbn/files/9982336/system.log)

[b274255a.zip](https://github.com/schollz/zxcvbn/files/9982345/b274255a.zip)

**Comment by schollz** [comment]
thanks @rbrt-fm ! I see the error. it looks like the samples didn't get put into the archive. I'm not sure why this happened, but I will take a look!

**Comment by schollz** [comment]
okay, I pushed a fix (https://github.com/schollz/zxcvbn/commit/98ef6fc32709f957594967cf65220f1b52c81178) that should solve this problem. I'll release an update (v.1.3.0) that includes this and other things tomorrow

**Comment by rbrt-fm** [comment]
sweet! 
i tried to update with `git fetch --all` and `git checkout acrostic` but after pressing K3 to run install again maiden says `INSTALL NEEDED: acrostic`

**Comment by schollz** [comment]
that should be fixed now! I forgot to update the release with acrostic binaries

**Comment by rbrt-fm** [comment]
sorry for the late reply, i've been busy making hella tracks with zxcvn! tli is such a fun way to approach composition, i haven't been this excited recording things in quite a while.

unfortunately i'm still having trouble with getting the archives to load the text and clades (this isn't a huge deal for me as i don't normally save things, but i wanted to help with bug reporting). perhaps i'm misunderstanding the procedure though, is it necessary to save then load a pset after loading the archive?

also, i'm still seeing the weird behavior where it is saving/creating a new archive every time i try and load one.

**Comment by schollz** [comment]
thanks! yeah I see the bug, I think again I've fixed it? I will release it with 1.5, try it out and let me know.

for the procedure - you shouldn't have to load the PSET after loading the archive. archives are like a super-charged PSET, they will collect all your sample files - useful for sharing data but comes at the cost of higher disk usage (since it duplicates sample files)

**Comment by rbrt-fm** [comment]
works like a charm!
